from __future__ import annotations

from pathlib import Path

import yaml
from rich.console import Console

from ai.instructions import generate_agent_instructions
from contracts.models import Contract, ProjectConfig

console = Console()


def detect_project(root: Path) -> dict[str, bool]:
    return {
        "Python": any(root.glob("*.py")) or (root / "pyproject.toml").exists(),
        "FastAPI": _grep_dependency(root, "fastapi"),
        "Docker": (root / "Dockerfile").exists(),
        "Terraform": any(root.glob("**/*.tf")),
        "AWS": _grep_any(root, ["aws_", 'provider "aws"']),
        "PostgreSQL": _grep_any(root, ["postgres"]),
        "GitHub Actions": (root / ".github" / "workflows").exists(),
    }


def _grep_dependency(root: Path, name: str) -> bool:
    for candidate in ("pyproject.toml", "requirements.txt"):
        f = root / candidate
        if f.exists() and name in f.read_text().lower():
            return True
    return False


def _grep_any(root: Path, needles: list[str]) -> bool:
    for tf in list(root.glob("**/*.tf"))[:50]:
        text = tf.read_text().lower()
        if any(n.lower() in text for n in needles):
            return True
    return False


def build_starter_contract(project_name: str) -> Contract:
    return Contract(project=ProjectConfig(name=project_name))


def run_init(project_root: str = ".") -> None:
    root = Path(project_root).resolve()
    contract_path = root / "infra-contract.yaml"

    detected = detect_project(root)
    console.print("[bold]Detected:[/bold]\n")
    for name, found in detected.items():
        mark = "[green]✓[/green]" if found else "[dim]·[/dim]"
        console.print(f"{mark} {name}")

    if contract_path.exists():
        console.print(f"\n[yellow]infra-contract.yaml already exists at {contract_path}[/yellow]")
    else:
        contract = build_starter_contract(project_name=root.name)
        contract_dict = contract.model_dump(mode="json", exclude_none=True, by_alias=True)
        contract_path.write_text(
            "# infra-contract.yaml — generated by `infra-contract init`\n"
            "# Edit this file to describe what your infrastructure is allowed to do.\n\n"
            + yaml.safe_dump(contract_dict, sort_keys=False)
        )
        console.print(f"\n[green]✓[/green] Created {contract_path.name}")

    policies_dir = root / "infra-contract" / "policies"
    policies_dir.mkdir(parents=True, exist_ok=True)
    console.print("[green]✓[/green] Created policy directory")

    contract = build_starter_contract(project_name=root.name)
    agents_md = root / "AGENTS.md"
    claude_md = root / "CLAUDE.md"
    instructions = generate_agent_instructions(contract)
    for path in (agents_md, claude_md):
        if not path.exists():
            path.write_text(instructions)
    console.print("[green]✓[/green] Created agent instructions (AGENTS.md, CLAUDE.md)")

    workflow_dir = root / ".github" / "workflows"
    workflow_dir.mkdir(parents=True, exist_ok=True)
    workflow_path = workflow_dir / "infra-contract.yml"
    if not workflow_path.exists():
        workflow_path.write_text(_GITHUB_WORKFLOW)
        console.print("[green]✓[/green] Created GitHub Actions workflow")

    console.print("\nRun:\n\n    infra-contract check\n\nto validate your project.")


_GITHUB_WORKFLOW = """\
name: Infrastructure Contract

on:
  pull_request:
    paths:
      - "terraform/**"
      - "infra-contract.yaml"

jobs:
  contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Install infra-contract
        run: pip install infra-contract
      - name: Check contract
        run: infra-contract check --format json --fail-on high
"""
